version: '3'

services:

  web:
    build:
      context: ../../docker/build/${ENV:-dev}/nginx
    volumes:
      - ../../${WEB_WWW_PATH:-src/test/}:/var/www
      - ../build/${ENV:-dev}/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../build/${ENV:-dev}/nginx/sites/:/etc/nginx/sites-available
      - ../build/${ENV:-dev}/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - ${WEB_HTTP_PORT:-80}:80
      - ${WEB_HTTPS_PORT:-443}:443
    depends_on:
      - php

  php:
    build:
      context: ../../docker/build/${ENV:-dev}/php-fpm
    volumes:
      - ../../${WEB_WWW_PATH:-src/test/}:/var/www